apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: strh7fifb-python
  janus-idp.io/tekton: strh7fifb-python
  backstage.io/kubernetes-id: strh7fifb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: strh7fifb-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
