apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: strh7fifb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: strh7fifb-python 
  name: strh7fifb-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: strh7fifb-python
    weight: 100 
