apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: strh7fifb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: strh7fifb-python 
  name: strh7fifb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: strh7fifb-python 
